stages:
  - test-ci

variables:
  DOCKER_FILE: "Dockerfile"
  DOCKER_REGISTRY: "docker.io"
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_IMAGE_NAME: "bbertka/temporal-review-analyzer"  # Base image name
  DOCKER_BASE_TAG: "latest"  # Base tag

local-test:
  stage: test-ci
  image: python:3.8
  script:
    - set -e  # Exit immediately if a command exits with a non-zero status.
    - pip3 install -r requirements.txt  # Install dependencies.
    - python3 src/main.py &> /dev/null &  # Start app in the background, suppress output.
    - sleep 5  # Give Flask some time to start.
    - |
      response=$(curl --fail -s "http://localhost:5000/sentiment?item=B0CJVL51V9")
      echo "Response: $response"
      if ! echo "$response" | grep -q '"item": "B0CJVL51V9"'; then
        echo "Test failed: B0CJVL51V9 sentiment not available."
        exit 1
      fi
    - kill $!  # Stop the Flask app.
  only:
    - main
