stages:
  - test-ci

variables:
  DOCKER_FILE: "Dockerfile"
  DOCKER_REGISTRY: "docker.io"
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_IMAGE_NAME: "bbertka/temporal-review-analyzer"  # Base image name
  DOCKER_BASE_TAG: "latest"  # Base tag

local-test:
  stage: test-ci
  image: python:3.8
  before_script:
    - apt-get update && apt-get install -y jq
    - pip install -r requirements.txt
  script:
    - |
      python src/main.py &> /dev/null & 
      sleep 5  # Allow some time for the server to start.
      response=$(curl --fail -s "http://localhost:5000/sentiment?item=B0CJVL51V9")
      echo "Response: $response"
      if ! echo "$response" | jq -e '.result != null and .verdict != null'; then
        echo "Test failed: 'result' or 'verdict' is null."
        exit 1
      else
        echo "Test passed: Both 'result' and 'verdict' are present and not null."
      fi
  only:
    - main
