apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-review-analyzer-deployment
  labels:
    app: temporal-review-analyzer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: temporal-review-analyzer
  template:
    metadata:
      labels:
        app: temporal-review-analyzer
    spec:
      containers:
      - name: temporal-review-analyzer
        image: bbertka/temporal-review-analyzer:latest-arm64
        ports:
        - containerPort: 5000
        env:
        - name: AMAZON_USERNAME
          value: "${AMAZON_USERNAME}"
        - name: AMAZON_PASSWORD
          value: "${AMAZON_PASSWORD}"
        - name: TEMPORAL_HOST
          value: "${TEMPORAL_HOST}"
        - name: TEMPORAL_PORT
          value: "${TEMPORAL_PORT}"
        - name: REDIS_HOST
          value: "${REDIS_HOST}"
        - name: REDIS_PORT
          value: "${REDIS_PORT}"
        - name: REDIS_DB
          value: "${REDIS_DB}"
        - name: PORT
          value: "${PORT}"
        - name: OPENAI_API_KEY
          value: "${OPENAI_API_KEY}"


---
apiVersion: v1
kind: Service
metadata:
  name: temporal-review-analyzer-service
spec:
  selector:
    app: temporal-review-analyzer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: ${PORT}
  type: LoadBalancer
