apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-review-analyzer-deployment
  labels:
    app: temporal-review-analyzer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: temporal-review-analyzer
  template:
    metadata:
      labels:
        app: temporal-review-analyzer
    spec:
      containers:
      - name: temporal-review-analyzer
        image: bbertka/temporal-review-analyzer-arm64:latest
        ports:
        - containerPort: 5000
        env:
        - name: AMAZON_USERNAME
          value: "changeme"
        - name: AMAZON_PASSWORD
          value: "changeme"
        - name: TEMPORAL_HOST
          value: "192.168.1.114"
        - name: TEMPORAL_PORT
          value: "7233"
        - name: REDIS_HOST
          value: "192.168.1.110"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: PORT
          value: "5000"
        - name: OPENAI_API_KEY
          value: "changeme"


---
apiVersion: v1
kind: Service
metadata:
  name: temporal-review-analyzer-service
spec:
  selector:
    app: temporal-review-analyzer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
